/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TaxpayerApiOverviewImport } from './routes/taxpayer-api-overview'
import { Route as IndexImport } from './routes/index'
import { Route as CommonapiIndexImport } from './routes/commonapi/index'
import { Route as TaxpayerReturnsIndexImport } from './routes/taxpayer/returns/index'
import { Route as CommonapiApiVersionApiEndpointImport } from './routes/commonapi/$apiVersion.$apiEndpoint'
import { Route as CommonapiApiVersionApiSubTypeApiEndpointImport } from './routes/commonapi/$apiVersion.$apiSubType.$apiEndpoint'

// Create/Update Routes

const TaxpayerApiOverviewRoute = TaxpayerApiOverviewImport.update({
  path: '/taxpayer-api-overview',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CommonapiIndexRoute = CommonapiIndexImport.update({
  path: '/commonapi/',
  getParentRoute: () => rootRoute,
} as any)

const TaxpayerReturnsIndexRoute = TaxpayerReturnsIndexImport.update({
  path: '/taxpayer/returns/',
  getParentRoute: () => rootRoute,
} as any)

const CommonapiApiVersionApiEndpointRoute =
  CommonapiApiVersionApiEndpointImport.update({
    path: '/commonapi/$apiVersion/$apiEndpoint',
    getParentRoute: () => rootRoute,
  } as any)

const CommonapiApiVersionApiSubTypeApiEndpointRoute =
  CommonapiApiVersionApiSubTypeApiEndpointImport.update({
    path: '/commonapi/$apiVersion/$apiSubType/$apiEndpoint',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/taxpayer-api-overview': {
      id: '/taxpayer-api-overview'
      path: '/taxpayer-api-overview'
      fullPath: '/taxpayer-api-overview'
      preLoaderRoute: typeof TaxpayerApiOverviewImport
      parentRoute: typeof rootRoute
    }
    '/commonapi/': {
      id: '/commonapi/'
      path: '/commonapi'
      fullPath: '/commonapi'
      preLoaderRoute: typeof CommonapiIndexImport
      parentRoute: typeof rootRoute
    }
    '/commonapi/$apiVersion/$apiEndpoint': {
      id: '/commonapi/$apiVersion/$apiEndpoint'
      path: '/commonapi/$apiVersion/$apiEndpoint'
      fullPath: '/commonapi/$apiVersion/$apiEndpoint'
      preLoaderRoute: typeof CommonapiApiVersionApiEndpointImport
      parentRoute: typeof rootRoute
    }
    '/taxpayer/returns/': {
      id: '/taxpayer/returns/'
      path: '/taxpayer/returns'
      fullPath: '/taxpayer/returns'
      preLoaderRoute: typeof TaxpayerReturnsIndexImport
      parentRoute: typeof rootRoute
    }
    '/commonapi/$apiVersion/$apiSubType/$apiEndpoint': {
      id: '/commonapi/$apiVersion/$apiSubType/$apiEndpoint'
      path: '/commonapi/$apiVersion/$apiSubType/$apiEndpoint'
      fullPath: '/commonapi/$apiVersion/$apiSubType/$apiEndpoint'
      preLoaderRoute: typeof CommonapiApiVersionApiSubTypeApiEndpointImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  TaxpayerApiOverviewRoute,
  CommonapiIndexRoute,
  CommonapiApiVersionApiEndpointRoute,
  TaxpayerReturnsIndexRoute,
  CommonapiApiVersionApiSubTypeApiEndpointRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/taxpayer-api-overview",
        "/commonapi/",
        "/commonapi/$apiVersion/$apiEndpoint",
        "/taxpayer/returns/",
        "/commonapi/$apiVersion/$apiSubType/$apiEndpoint"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/taxpayer-api-overview": {
      "filePath": "taxpayer-api-overview.tsx"
    },
    "/commonapi/": {
      "filePath": "commonapi/index.tsx"
    },
    "/commonapi/$apiVersion/$apiEndpoint": {
      "filePath": "commonapi/$apiVersion.$apiEndpoint.tsx"
    },
    "/taxpayer/returns/": {
      "filePath": "taxpayer/returns/index.tsx"
    },
    "/commonapi/$apiVersion/$apiSubType/$apiEndpoint": {
      "filePath": "commonapi/$apiVersion.$apiSubType.$apiEndpoint.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
